version: 40
jobs:
- name: Repo Sync Push
  steps:
  - !PushRepository
    name: Github push sync
    remoteUrl: https://github.com/VnUgE/nvault.git
    userName: VnUgE
    passwordSecret: github-access-token
    force: true
    condition: SUCCESSFUL
    optional: false
  - !PushRepository
    name: Codeberg push sync
    remoteUrl: https://codeberg.org/VnUgE/nvault.git
    userName: VnUgE
    passwordSecret: codeberg-access-token
    force: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !TagCreateTrigger {}
  - !BranchUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600