version: 53
jobs:
- name: GitHub Push
  steps:
  - type: PushRepository
    name: Github push sync
    remoteUrl: https://github.com/VnUgE/NVault.git
    userName: VnUgE
    passwordSecret: github-access-token
    force: true
    condition: SUCCESSFUL
    optional: false
  - type: PushRepository
    name: codeberg push sync
    remoteUrl: https://codeberg.org/vnuge/nvault.git
    userName: VnUgE
    passwordSecret: codeberg-access-token
    force: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: TagCreateTrigger
    projects: NVault
  - type: BranchUpdateTrigger
    userMatch: anyone
    projects: NVault
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  includeUpstreamWhenRebuild: false
  includeDownstreamWhenRebuild: false
  timeout: 3600
